### ISSUE TITLE
Error when not logged in as administrator

### ISSUE THREAD

**Issue by curtisdelicata** [magicsunday/webtrees-pedigree-chart#1]
Error: Call to a member function parameter() on null in file /modules_v4/webtrees-fan-chart/src/Traits/UtilityTrait.php on line 183
Stack trace:
  1. Error->() /modules_v4/webtrees-fan-chart/src/Traits/UtilityTrait.php:183
  2. MagicSunday\Webtrees\FanChart\Module->getColor() /modules_v4/webtrees-fan-chart/src/Module.php:124
  3. MagicSunday\Webtrees\FanChart\Module->getChartParameters() /modules_v4/webtrees-fan-chart/src/Module.php:90
  4. MagicSunday\Webtrees\FanChart\Module->getChartAction() [internal]:0
  5. ReflectionMethod->invoke() /app/Application.php:45
  6. Fisharebest\Webtrees\Application->dispatch() /app/Http/Controllers/ModuleController.php:82
  7. Fisharebest\Webtrees\Http\Controllers\ModuleController->action() [internal]:0
  8. ReflectionMethod->invoke() /app/Application.php:45
  9. Fisharebest\Webtrees\Application->dispatch() /index.php:156
 10. {closure}() /app/Module/HitCountFooterModule.php:185
 11. Fisharebest\Webtrees\Module\HitCountFooterModule->handle() /index.php:142
 12. {closure}() /app/Http/Middleware/CheckCsrf.php:64
 13. Fisharebest\Webtrees\Http\Middleware\CheckCsrf->handle() /index.php:142
 14. {closure}() /app/Http/Middleware/UseTransaction.php:43
 15. Fisharebest\Webtrees\Http\Middleware\UseTransaction->handle() /index.php:142
 16. {closure}() /app/Http/Middleware/Housekeeping.php:75
 17. Fisharebest\Webtrees\Http\Middleware\Housekeeping->handle() /index.php:142
 18. {closure}() /app/Http/Middleware/DebugBarData.php:42
 19. Fisharebest\Webtrees\Http\Middleware\DebugBarData->handle() /index.php:142
 20. {closure}() /app/Http/Middleware/BootModules.php:59
 21. Fisharebest\Webtrees\Http\Middleware\BootModules->handle() /index.php:142
 22. {closure}() /app/Http/Middleware/UseTheme.php:71
 23. Fisharebest\Webtrees\Http\Middleware\UseTheme->handle() /index.php:142
 24. {closure}() /app/Http/Middleware/UseLocale.php:52
 25. Fisharebest\Webtrees\Http\Middleware\UseLocale->handle() /index.php:142
 26. {closure}() /app/Http/Middleware/UseTree.php:58
 27. Fisharebest\Webtrees\Http\Middleware\UseTree->handle() /index.php:142
 28. {closure}() /app/Http/Middleware/UseSession.php:59
 29. Fisharebest\Webtrees\Http\Middleware\UseSession->handle() /index.php:142
 30. {closure}() /app/Http/Middleware/UseFilesystem.php:50
 31. Fisharebest\Webtrees\Http\Middleware\UseFilesystem->handle() /index.php:142
 32. {closure}() /app/Http/Middleware/CheckForMaintenanceMode.php:48
 33. Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->handle() /index.php:142
 34. {closure}() /index.php:159

**Comment by magicsunday** [comment]
Thanks
