### ISSUE TITLE
Missing translation for German 

### ISSUE THREAD

**Issue by hartenthaler** [magicsunday/webtrees-pedigree-chart#10]
There is one phrase which is not translated into German:

- Show empty boxes for missing individuals. Caution: May slow down your system!
- Leere Kästchen für fehlende Personen anzeigen. Achtung: dies kann ihr System verlangsamen!

**Comment by magicsunday** [comment]
Ich weiß. Da sich das Modul noch in Entwicklung befindet, gibt es noch diverse unfertige Stellen. :-)

**Comment by magicsunday** [comment]
Mit 5b0e6b00bc42da4b79fdb127100e50464ed9e9e5 hinzugefügt
