### ISSUE TITLE
1.1.0 - silhouette images are not displayed

### ISSUE THREAD

**Issue by TheDutchJewel** [magicsunday/webtrees-pedigree-chart#13]
The silhouette images (webtrees\modules_v4\webtrees-pedigree-chart\resources\images) are not loaded in my browsers (latest versions of Edge and Firefox) on Win10 x64 20H2.

Edge shows a default picture:
![image](https://user-images.githubusercontent.com/46184729/104084739-0af7c680-524a-11eb-8514-21a5e14b56eb.png)

Firefox shows no picture:
![image](https://user-images.githubusercontent.com/46184729/104084743-1519c500-524a-11eb-8012-fac5778ae92f.png)

Any idea how to fix this?

**Comment by magicsunday** [comment]
Are the images of the individuals loaded correctly?
Did the silhouette images got loaded in the previous version?

Please try the latest version from master branch. I added some error logging to the image loading method. Do you get any errors in the console log?

I do not get any errors in my Firefox and Edge.

**Comment by TheDutchJewel** [comment]
>Are the images of the individuals loaded correctly?

Which images? I don't use images.
Or do you mean the silhouette images in the standard pedigree chart and on the individual page?
These are displayed correctly. The only incorrect displayed images are the silhouette images in your nice Pedigree chart.


> Did the silhouette images got loaded in the previous version?

I didn't test the initial release, only v1.1.0.
But now also tested in v1.0.0: same problem.


>Please try the latest version from master branch.

Done. Same problem.


> I added some error logging to the image loading method. Do you get any errors in the console log?

Here's the content of the console log in Edge:
```
vendor.min.js?v=2.0.11:2 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

send @ vendor.min.js?v=2.0.11:2
ajax @ vendor.min.js?v=2.0.11:2
T._evalUrl @ vendor.min.js?v=2.0.11:2
Re @ vendor.min.js?v=2.0.11:2
append @ vendor.min.js?v=2.0.11:2
(anonymous) @ vendor.min.js?v=2.0.11:2
U @ vendor.min.js?v=2.0.11:2
html @ vendor.min.js?v=2.0.11:2
(anonymous) @ vendor.min.js?v=2.0.11:2
l @ vendor.min.js?v=2.0.11:2
fireWith @ vendor.min.js?v=2.0.11:2
x @ vendor.min.js?v=2.0.11:2
(anonymous) @ vendor.min.js?v=2.0.11:2
load (async)
send @ vendor.min.js?v=2.0.11:2
ajax @ vendor.min.js?v=2.0.11:2
T.fn.load @ vendor.min.js?v=2.0.11:2
(anonymous) @ webtrees.min.js?v=2.0.11:1
each @ vendor.min.js?v=2.0.11:2
each @ vendor.min.js?v=2.0.11:2
(anonymous) @ webtrees.min.js?v=2.0.11:1
u @ vendor.min.js?v=2.0.11:2
c @ vendor.min.js?v=2.0.11:2
setTimeout (async)
(anonymous) @ vendor.min.js?v=2.0.11:2
l @ vendor.min.js?v=2.0.11:2
fireWith @ vendor.min.js?v=2.0.11:2
fire @ vendor.min.js?v=2.0.11:2
l @ vendor.min.js?v=2.0.11:2
fireWith @ vendor.min.js?v=2.0.11:2
ready @ vendor.min.js?v=2.0.11:2
q @ vendor.min.js?v=2.0.11:2
```

Here's the content of the console log in Firefox:
```
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/
```

**Comment by magicsunday** [comment]
Strange. Maybe you can give me access to the site so that I can see for myself?

**Comment by TheDutchJewel** [comment]
I sent you an email with the link.

**Comment by magicsunday** [comment]
I did not get any mail

**Comment by TheDutchJewel** [comment]
Oops, I sent it to the wrong Ric...

New mail sent to you.

Anyway, I just installed a fresh webtrees as test, with only your Fan and Pedigree chart modules.

And I found something interesting: _photos_ are displayed correctly, _silhouette images_ are not displayed!

I've added two trees with a dummy info, one _with_ and one _without_ photos.

I tested your Pedigree chart on both trees:
tree _with_ photos:
-> photos are displayed correctly.

tree _without_ photos:
-> silhouette images are not displayed, while they are displayed correctly in the Fan chart.

I hope this will help to solve the problem.

**Comment by magicsunday** [comment]
Ok. Seems a problem with the pretty URLs I dont use until now.

**Comment by magicsunday** [comment]
I changed the way returning the images from the module. Now its up to webtrees to return the correct mime type for SVG images in order to display them correctly..

**Comment by magicsunday** [comment]
With latest webtrees master and with latest master from this repo, the error should be fixed.

**Comment by 06Games** [comment]
Even with the last commit, I also encounter this bug. This was not happening with the code of my pull request. You must have changed something that you shouldn't have in the meantime ;)
I will look tomorrow if I can fix that

**Comment by 06Games** [comment]
After investigation, it seems that in my case, it is https://github.com/magicsunday/webtrees-pedigree-chart/commit/8237be78315838c1a174ded6d982694fef5a22e5 which caused the problem. 
Before this one, I do not encounter any problem.

**Comment by magicsunday** [comment]
@TheDutchJewel Did it work for you?

**Comment by magicsunday** [comment]
@06Games You have to use latest version from *master*-branch of webtrees as this contains the fix. https://github.com/fisharebest/webtrees/commit/91694fa0fffbd96d0aeb70b934ccce9b3b4e82e2

**Comment by TheDutchJewel** [comment]
@magicsunday Yes, the latest version from the master-branch works fine with the latest webtrees master. Thanks for fixing!

And thanks to the [fix](https://github.com/fisharebest/webtrees/commit/91694fa0fffbd96d0aeb70b934ccce9b3b4e82e2) you mentioned, I can use your Pedigree chart in the stable webtrees version too!
