### ISSUE TITLE
Missing silhouette

### ISSUE THREAD

**Issue by mrqd9** [magicsunday/webtrees-pedigree-chart#15]
Hello.
I'am getting broken image icons on individuals without media, why not the silhouette should be displayed instead of that icon?

![20210126_013028](https://user-images.githubusercontent.com/56225476/105759380-67f7ba00-5f76-11eb-86a9-4e34391a5d6e.jpg)

**Comment by magicsunday** [comment]
This has already be fixed in webtrees master branch. See https://github.com/fisharebest/webtrees/pull/3665
