### ISSUE TITLE
coding error: &nbsp;

### ISSUE THREAD

**Issue by hartenthaler** [magicsunday/webtrees-pedigree-chart#18]
![Screenshot (219)_LI](https://user-images.githubusercontent.com/6324175/111230412-e02e4380-85e7-11eb-860d-6ddab602cb43.jpg)

**Comment by magicsunday** [comment]
Wie bekommt man denn solche Datumsangaben hin?

**Comment by hartenthaler** [comment]
Eingabe eines Datums unter Verwendung des julianischen Kalenders (etwa beim Todestag von Eleanor de Castilla):
`2 DATE @#DJULIAN@ 29 NOV 1290`.
Alle Datumsangaben ohne @#DJULIAN@ sind laut GEDCOM-Standard Gregorianische Datumsangaben, aber diesen Kalender gab es damals ja noch nicht.
