### ISSUE TITLE
Number of possible generations

### ISSUE THREAD

**Issue by mpwt** [magicsunday/webtrees-pedigree-chart#24]
Könnte die max. Generationsanzahl reduziert werden? Die aktuell wählbaren 25 Generationen lassen die Internetseite "einfrieren". Eine maximale Anzahl von 10-15 sollte an sich ausreichen, zumal die Lesbarkeit da schon stark abgenommen hat.

**Comment by magicsunday** [comment]
Die Anzahl würde ich nicht reduzieren. Aktuell hab ich 17 darstellbare Generationen in meinem Stammbaum ;-). Die hohe Anzahl hatte ich gewählt, um den Baum (nach Export) auch mal vollständig drucken zu können.

Man könnte ggf. darüber nachdenken, dass man in den Einstellungen von Webtrees eine Pluginkonfiguration einführt in der man Voreinstellungen für das Formular hinterlegt, so dass man dann dort z.B. die maximale Anzahl begrenzen könnte die im Formular dann zur Verfügung steht.

Ins Formular selbst könnte man noch einen zusätzlichen Hinweise einfügen, dass bei >20 Generationen es ggf. zum Einfrieren der Seite kommen kann auf Grund der hohe Datenmenge.
