### ISSUE TITLE
Names

### ISSUE THREAD

**Issue by vytux-com** [magicsunday/webtrees-pedigree-chart#3]
Name display seems weird especially if persons have middle names.

e.g. John /Smith/ is displayed as J. Smith which is OK i suppose. 
John Peter /Smith/  is displayed as J. Peter Smith now is is completely incorrect as if we did have to shorten the name it should be John P Smith. So the middle name gets truncated no first

**Comment by magicsunday** [comment]
Yes, I know, this module is still work in progress. Currently I have not much time to proceed with the development.

**Comment by hartenthaler** [comment]
I just installed your module. Nice design! Regarding name: I like the reduced set of information which is displayed. I would prefer not to show nicknames, but to show birth and death years.

**Comment by magicsunday** [comment]
Should be fixed now. Names are now equally treated as in webtrees-fan-chart module.
