### ISSUE TITLE
add option to show all relatives

### ISSUE THREAD

**Issue by yako1984** [magicsunday/webtrees-pedigree-chart#30]
The option of being able to show all the individuals in the tree, such as brothers, uncles, etc. would be a good idea.

**Comment by 06Games** [comment]
Related to https://github.com/magicsunday/webtrees-descendants-chart/issues/3

**Comment by wp4711** [comment]
would like to see this option too. It would really be nice to see spouse and other relatives

**Comment by h4kk1** [comment]
I think as well that this will be great

**Comment by magicsunday** [comment]
- ? The spouse of the selected individual?
- ? What other relatives? As this is an ancestor chart, how much sense would this do? In the descendants chart I think thats makes more sense.

**Comment by hartenthaler** [comment]
For me that makes no sense in an ancestor diagram.

**Comment by magicsunday** [comment]
Closed due missing answers from thread opener.
