### ISSUE TITLE
Layout incorrect on RTL languages

### ISSUE THREAD

**Issue by ddrury** [magicsunday/webtrees-pedigree-chart#31]
![demo](https://user-images.githubusercontent.com/104515/131357241-68ba7cf3-eea8-48e2-b3e4-094de9c3a1a6.jpg)

**Comment by magicsunday** [comment]
Could you please provide me a sample record (and how it is should look), so I could easier reproduce this?

**Comment by ddrury** [comment]
Gedcom & image files attached, not same person as the image above but effect is the same. The Persons name should be to the right of the thumbnail image
![demo](https://user-images.githubusercontent.com/104515/145890247-4b06daa9-92be-4a1e-853a-5c9ee4412969.jpg)
[clippings.zip](https://github.com/magicsunday/webtrees-pedigree-chart/files/7707014/clippings.zip)

**Comment by magicsunday** [comment]
Thanks. I thought there was something special inside the gedcom regarding RTL, thats why I asked about.

**Comment by ddrury** [comment]
>  I thought there was something special inside the gedcom regarding RTL

Haha - I'm not that clever
