### ISSUE TITLE
JSON-THROW-ON-ERROR

### ISSUE THREAD

**Issue by benetel** [magicsunday/webtrees-pedigree-chart#32]
Hi,
I use Webtrees 2.0.16
As I activate the the pedigree chart custom module (v 1.2.5) and try to display it on my webtrees pages, the resuls is an error message :

"use of undefined constant JSON-THROW-ON-ERROR,
as shown in the image

![image](https://user-images.githubusercontent.com/90130251/132120045-a793b3f1-81c2-4022-9d4b-082c6a43ec2c.png)

**Comment by 06Games** [comment]
It seems that this error is due to a version of PHP lower than 7.3. I advise you to update your PHP installation in order to fix this problem. 
https://www.php.net/manual/fr/json.constants.php

**Comment by ddrury** [comment]
Nevertheless, it's best practice to declare constants as well as classes, eg

`use const JSON_THROW_ON_ERROR;`

**Comment by magicsunday** [comment]
I created a new release for PHP 7.1 to remove this dependency. Nevertheless you should upgrade your PHP version as 7.1 is outdated.
