### ISSUE TITLE
Track upstream

### ISSUE THREAD

**Issue by ddrury** [magicsunday/webtrees-pedigree-chart#33]
Upstream commit https://github.com/fisharebest/webtrees/commit/d4786c66945cca20d5ce34ac3cf08cf5a5110ae2 changed data attributes.

Need to change modules_v4\webtrees-pedigree-chart\resources\views\modules\pedigree-chart\page.phtml lines 214/215 to
```
document.getElementById("pedigree-chart-url")
    .setAttribute('data-wt-ajax-url', ajaxUrl);
```

Change also required in descendants chart

**Comment by magicsunday** [comment]
Thanks. Is fixed in latest master.
