### ISSUE TITLE
webtrees-2.1 necessary changes

### ISSUE THREAD

**Issue by ddrury** [magicsunday/webtrees-pedigree-chart#38]
The following changes to `webtrees-pedigree-chart\resources\views\modules\pedigree-chart\page.phtml` are required to meet webtrees-2.1 requirements

lines 114/115 change data-toggle to data-bs-toggle
line 230 change data-ajax-url to data-wt-ajax-url

**Comment by magicsunday** [comment]
see [@branch2.1](https://github.com/magicsunday/webtrees-pedigree-chart/tree/2.1)

**Comment by ddrury** [comment]
Apologies
