### ISSUE TITLE
error:  Declaration of MagicSunday

### ISSUE THREAD

**Issue by Alien-hide** [magicsunday/webtrees-pedigree-chart#4]
Global php error, after add this model to modules_v4 directory.
Webtrees ver 2.0.7

`[Sat Aug 22 17:19:53.734742 2020] [php7:error] [pid 23865] [client 172.69.10.76:20708] PHP Fatal error:  Declaration of MagicSunday\\Webtrees\\PedigreeChart\\Traits\\UtilityTrait::boot(Fisharebest\\Webtrees\\Module\\ModuleThemeInterface $theme): void must be compatible with Fisharebest\\Webtrees\\Module\\PedigreeChartModule::boot(): void in /var/www/html/webtrees/modules_v4/webtrees-pedigree-chart/src/Module.php on line 30
`

You may it fix it?

**Comment by magicsunday** [comment]
Fixed.

**Comment by Alien-hide** [comment]
Awesom! thx!
