### ISSUE TITLE
Chart is not displayed #2

### ISSUE THREAD

**Issue by ThomasT02** [magicsunday/webtrees-pedigree-chart#43]
**Describe the bug**
I see the same as h4kk1 described in #41.
A "loading circle" is displayed, pressing any button (Show additional options; Display; Center; Export) doesn't work.

I am using php 8 and MariaDB 10 and webtrees 2.1.0-alpha.1 and webtrees-pedigree-chart 1.2.8.
The file /webtrees/data/config.ini.php contains base_url="https://mydomain.de/webtrees".
README.md says 'Requires webtrees 2.0'. Does that mean I should downgrade to webtrees 2.0?

**Comment by magicsunday** [comment]
Please use the 2.1 branch as there is currently no 2.1 Release of the Chart.

**Comment by ThomasT02** [comment]
It works. Very nice and good looking. Thx. Issue  closed.

Some "wishes" btw:
- Can we expect a similar version, starting from the past and looking to the future (Stammbaum vs. Ahnentafel)?
- Would be nice to edit the view (distancen between cards, size of radius, content, font, size)
- Large tables are not readeble because of fitting into the viewable area. Changing the number of generatons shouldn't change the zoom.

**Comment by magicsunday** [comment]
You could zoom in/out using the mousewheel or your fingers on touch devices.

**Comment by ThomasT02** [comment]
I was following your hint above and this works.
