### ISSUE TITLE
Changelog info

### ISSUE THREAD

**Issue by AlexKalopsia** [magicsunday/webtrees-pedigree-chart#44]
Hi, this is not really a request for the module itself, but it would be great if when a new version is released, you could list the changes in the changelog (ie https://github.com/hartenthaler/hh_extended_family/releases). It would make it a lot easier to understand if an update is useful for the user or not. 

Either way, thanks for the great work on the pedigree chart!

**Comment by magicsunday** [comment]
I will try my best :)
