### ISSUE TITLE
Improve mobile browsing experience

### ISSUE THREAD

**Issue by DaPoHou** [magicsunday/webtrees-pedigree-chart#48]
Thank you for such a great module! Especially on mobile devices.
If possible, it is recommended to improve the following two experiences:

1.When browsing the page with the mobile phone, the chart occupies most of the page. 
When the page height is higher than the screen of the mobile phone, it is necessary to slide the screen up and down with one finger, but the finger cannot scroll the screen when the chart slides.
Can the code make the page scroll up and down when the single finger slides up and down on the chart?

2. When the mouse hovers or the finger clicks on the individual box(Or there is a "view details" text link), the detailed information of the individual can be displayed.

**Comment by magicsunday** [comment]
Please open a new issue for your second request.
