### ISSUE TITLE
Error putting surnames between slashes

### ISSUE THREAD

**Issue by yako1984** [magicsunday/webtrees-pedigree-chart#52]
**Describe the bug**
Webtrees advises you if there are two surnames put them like this David /Gómez/ /Iglesias/ between two slashes:

Info Webtrees: "If there are two surnames, each must have bars: José Antonio /Gómez/ /Iglesias/"

But if you do the first surname is repeated twice. To solve it I have to put the two surnames between the same bars: /Gómez Iglesias/

**Screenshots**
![Screenshot_2](https://user-images.githubusercontent.com/67491705/176529821-8a996c1a-1597-4433-84f8-23df7c821ffd.jpg)

**Comment by magicsunday** [comment]
Should be fixed with [@webtrees-module-base:](https://github.com/magicsunday/webtrees-module-base/commit/83a07949e3e0d63f2bcba8ed24129922ded67a71)
