### ISSUE TITLE
1.2.8 keep loading in webtrees 2.1.16

### ISSUE THREAD

**Issue by fire4wd** [magicsunday/webtrees-pedigree-chart#57]
**Describe the bug**
the pedigree chart keep loading (inifinite turning wheel)

**To Reproduce**
1. Go to one individual page
2. select pedigree-chart

**Expected behavior**
loadin pedigre

**Screenshots**
![image](https://user-images.githubusercontent.com/16142597/224470308-5660e7d7-38a4-408c-9e70-4f17ded5ae43.png)

**Desktop (please complete the following information):**
 - Chrome, Edge, Brave
 - Webtrees version 2.1.16
 - Version of pedigree chart 1.2.8

**Additional context**

**Comment by magicsunday** [comment]
Please try latest release. 1.2.8 is over a year old.

**Comment by fire4wd** [comment]
I did try that too. 
Site dosn't load. Im gonna  go create a new issue

**Comment by magicsunday** [comment]
Any error messages in Browser or console?

**Comment by fire4wd** [comment]
when I go to on person page and select pedigree-chart this is what I get 

Class "MagicSunday\Webtrees\ModuleBase\Processor\NameProcessor" not found …/modules_v4/webtrees-pedigree-chart/src/Module.php:287
#0 …/modules_v4/webtrees-pedigree-chart/src/Module.php(252): MagicSunday\Webtrees\PedigreeChart\Module->getIndividualData(Object(Fisharebest\Webtrees\Individual), 1)
#1 …/modules_v4/webtrees-pedigree-chart/src/Module.php(176): MagicSunday\Webtrees\PedigreeChart\Module->buildJsonTree(Object(Fisharebest\Webtrees\Individual))

when I go to control panel I get this 

![image](https://user-images.githubusercontent.com/16142597/224494187-766c3642-6f78-432b-9321-760554bd7d32.png)

**Comment by magicsunday** [comment]
You are using the master branch. This is intented to be used with the upcoming Version 2.2 of webtrees. For webtrees 2.1 please use https://github.com/magicsunday/webtrees-pedigree-chart/releases/tag/1.5.0

**Comment by magicsunday** [comment]
The Master branch is the current develop Version and can only be installed using composer.

**Comment by fire4wd** [comment]
I see . sorry for the mess  :-(
