### ISSUE TITLE
Show hebrew names on pedigree chart analog webtrees native chart

### ISSUE THREAD

**Issue by cholowiss** [magicsunday/webtrees-pedigree-chart#60]
The charts that you have created are splendid as they present much better and I can do up to 25 generations.

What I miss is the possibility to have my hebrew names on the box.
Even better would be the possibility to configure exactly what should be shown, which names, how formatted, which dates and places and how formatted.
Original:
<img width="435" alt="pedigree chart webtrees" src="https://user-images.githubusercontent.com/84067252/236683414-98790047-5afb-4ba2-910b-4a35052089e4.png">
Your version:

<img width="472" alt="pedigree chart magicsunday" src="https://user-images.githubusercontent.com/84067252/236683452-358732a5-1264-4959-a1b0-10cd8f84054c.png">

Sorry about my previous issue, I hope this one makes it clear.

**Comment by magicsunday** [comment]
Hi, could you please attach a sample gedcom file with some individuals with hebrew names?

**Comment by magicsunday** [comment]
Hm, somehow the example gedcom file is still missing. Can you please upload them again or email (mail@ricosonntag.de) them to me directly?

**Comment by magicsunday** [comment]
Should be fixed with https://github.com/magicsunday/webtrees-pedigree-chart/commit/0f61ec9e987b9a93d9072d2cb7dbf39017c027e7

**Comment by cholowiss** [comment]
Hello Rico
Thank you very much for adding the hebrew (alternate) name support to your report.
I now see that my requirements are much more complicated (I need also the hebrew death date etc.) no cross as a death sign etc.
I know a little programming.
Could you direct me how I can copy your report and adapt it to my special needs?
Best regards
Salomon
