### ISSUE TITLE
not an issue, a question

### ISSUE THREAD

**Issue by aime44** [magicsunday/webtrees-pedigree-chart#62]
Hi magicsunday.
Thanks for your script.
I don't know if it's the best place to ask a thing, in the webtrees forum they said to go here.

I use this script and i search a solution to open a new window on click to go in the individual page.

I don't know javascript.
Maybe the the to modify is this?

`function(){t.personClick(e.data)}))}))}personClick(t){1!==t.generation?this.redirectToIndividual(t.url):this.update(t.updateUrl)}redirectToIndividual(t){window.location=t}update(t){window.location=t}}`

but how?

thank you

**Comment by magicsunday** [comment]
Hi. 

I think you could replace the `window.location=t` in` redirectToIndividual(t){window.location=t} `with something like this `window.open(t, "_blank");`

**Comment by magicsunday** [comment]
Added with https://github.com/magicsunday/webtrees-pedigree-chart/commit/f394fa67e8b7324024b5317d2b6d57a38fda01bc
