### ISSUE TITLE
Installation instructions in the readme

### ISSUE THREAD

**Issue by BertKoor** [magicsunday/webtrees-pedigree-chart#63]
Some feedback for you after I answered a forum post https://www.webtrees.net/index.php/en/forum/help-for-release-2-1-x/38067-issue-after-installing-webtrees-pedigree-chart-module

The readme with installation instructions is not very clear for typical non-technical end users.
Perhaps it's better to start with the steps they need to do. Currently it starts with Composer and Git, and there is no clue for the reader whether these are three ways to achieve the same, or whether all three paragraphs need to be executed in series.

Then after all the installation steps for end users are complete (they do want the manual install, right?) start a separate chapter for developers that want to run it from the raw source code or cloned repo.

**Comment by magicsunday** [comment]
Hi. Could you please take a look at the update README (https://github.com/magicsunday/webtrees-pedigree-chart/blob/master/README.md). What do you think, are the changes sufficient and understandable for non-technical users?
