### ISSUE TITLE
Black & White chart blocks

### ISSUE THREAD

**Issue by papjul** [magicsunday/webtrees-pedigree-chart#64]
**Describe the bug**
Sometimes between 4bf28a56362acaa182cae6b627e616280c0e15ea and v1.6.1, charts added as blocks on pages became colorless.
Issue did not happen in previous version or when #59 was submitted

**To Reproduce**
Pre-requisite:
Modules:
- default pedigree chart from Webtrees must be disabled
- webtrees-pedigree-chart must be enabled

1. Go to homepage tree
2. Add a chart block of type "Pedigree"
3. Come back to homepage
4. See chart in black and white

**Expected behavior**
Chart should be colored.

**Screenshots**
![image](https://github.com/magicsunday/webtrees-pedigree-chart/assets/1449159/87b10ebb-d096-4ef8-b601-282d249b7c5e)

**Desktop (please complete the following information):**
 - Browser: Chrome, Firefox
 - Webtrees version: 2.1.18
 - Version of pedigree chart: 1.6.1

**Additional context**
Real-life example here: https://gene.amenysta.net/tree/papasian

**Comment by magicsunday** [comment]
The only drawback of the solution is now, multiple includes of the CSS files, but there seems to be no other way to solve it in Webtrees at the moment.

https://github.com/fisharebest/webtrees/issues/4908
