### ISSUE TITLE
The Chinese surname and first name are in the wrong position

### ISSUE THREAD

**Issue by xiaoyang2013** [magicsunday/webtrees-pedigree-chart#67]
In the displayed chart, the position of the Chinese surname and first name is wrong. 
The Chinese name should have the surname first and the first name last. This problem does not exist in version 1.6.1.

**Comment by magicsunday** [comment]
Could you please add a sample gedcom with chinese names?

**Comment by zhoueysun** [comment]
@magicsunday 
You can use my clipping cart gedcom with Chinese names
[clippings.zip](https://github.com/magicsunday/webtrees-pedigree-chart/files/13953589/clippings.zip)

**Comment by magicsunday** [comment]
@zhoueysun 

Could you please test with latest version from branch "2.1" if https://github.com/magicsunday/webtrees-pedigree-chart/commit/89ad46481306b2b8daaaa9ef82fb1334a38ed21b fixes your issue?

**Comment by zhoueysun** [comment]
Yes! The issue appears fixed. I would like the opinion of the original poster @xiaoyang2013 and how it compared with v. 1.6.1 . I am happy.

**Comment by xiaoyang2013** [comment]
Yes, version 1.6.1 has solved this problem, and the test on webtrees2.1.18 is also normal.
