### ISSUE TITLE
Question: How do I get less space between name and dates

### ISSUE THREAD

**Issue by JustCarmen** [magicsunday/webtrees-pedigree-chart#68]
I am using your charts with minor modifications.

I noticed the boxes in the latest version are larger than before. As a result, there is much more unused and unnecessary space between the names and the dates.

Old version:
![Snag_30dd73ec](https://github.com/magicsunday/webtrees-pedigree-chart/assets/5641963/466ae3d7-3b40-4270-959f-b1c58aac45c5)

Current version:
![Snag_30de28c4](https://github.com/magicsunday/webtrees-pedigree-chart/assets/5641963/ceafb99c-438c-4fbc-ada7-fc230876bf4f)

You probably have your reasons for this change, but I like more the compact layout of the previous version. So I tried to get it back, but I can't get it to work:

I figured out that I should change LAYOUT_VERTICAL_NODE_WIDTH en LAYOUT_VERTICAL_NODE_HEIGHT  in resources\js\modules\lib\constants.js. I reset the values to the old values (150 and 175).

But then I get this:
![Snag_30ed6121](https://github.com/magicsunday/webtrees-pedigree-chart/assets/5641963/31cd8884-6713-4b1f-b07f-f0840dd25044)

The dates are outside the box

And now I am stuck. What else should I change?

**Comment by magicsunday** [comment]
The extra space is used for the alternative name of an individual, as its currently not possible to create boxes with different heights.

![grafik](https://github.com/magicsunday/webtrees-pedigree-chart/assets/564393/d3e39e6a-c548-4665-a248-3c8e6b828874)

**Comment by xiaoyang2013** [comment]
![314504056-3a8f9b50-bb2a-4cfb-a362-fe026119d1b6](https://github.com/magicsunday/webtrees-pedigree-chart/assets/139220146/a390187e-cc63-4cc2-8c5f-1c7f0b0ec703)
Where can I see this configuration? I did not find this interface after version 1.7.1.

**Comment by JustCarmen** [comment]
Thanks Rico for this fix. Works fine.

@xiaoyang2013 This code has been added to the development version and will be part of the next release.
