### ISSUE TITLE
feature request: export as png and svg

### ISSUE THREAD

**Issue by hartenthaler** [magicsunday/webtrees-pedigree-chart#7]
I know that you have not much time, but I like the design of your module and the possibility to get an overview showing many generations.

It would be nice to export the generated tree as png and svg,

**Comment by magicsunday** [comment]
Its now included

**Comment by hartenthaler** [comment]
... but there are no control elements / buttons for this function!

**Comment by magicsunday** [comment]
Maybe you are not using the latest version?

**Comment by hartenthaler** [comment]
ok, now the buttons are there and they are working as expected.

Vielen Dank! Damit ist das Modul schon richtig gut nutzbar!
