### ISSUE TITLE
There wasn't enough space to store 'layout' with value 'right' in the local storage.

### ISSUE THREAD

**Issue by HRN65** [magicsunday/webtrees-pedigree-chart#71]
**Describe the bug**
Using Edge browser, the Pedigree chart (latest version from branch 2.1), does not show in right orientation when "Show alternative name of individual" is unticked.
If "Show alternative name of individual" is ticked, the right orientation is displayed, but then unticking "Show alternative name of individual" does not take action.

No problem in Chrome, Firefox, Vivaldi and Brave

Console:
There wasn't enough space to store Asset?asset=js%2Fpedigree-chart-storage.min.js&hash=1712152959:1 'layout' with value 'right' in the local storage.

(The same error is seen i Descendants chart)

Settings in control panel:
Generations: 4
Orientation right
Layout: all unticked

**To Reproduce**
Feel free to test at
https://visitusinmaputo.com/webtree/tree/familie/webtrees-pedigree-chart/I89?generations=4&showEmptyBoxes=0&layout=up&openNewTabOnClick=0&showAlternativeName=0)]

**Desktop (please complete the following information):**
 - Browser: Edge
 - Webtrees version: 2.1.19
 - Version of pedigree chart: latest version from branch 2.1

**Comment by magicsunday** [comment]
I'm sorry, but I can't understand the problem. For me, your site works correctly in Edge. No error in the console.

Please check how much memory is being used in your Edge and delete it and then try again.

If necessary, search for Local Storage and Microsoft Edge. I quickly found this, maybe it will help:

https://learn.microsoft.com/de-de/microsoft-edge/devtools-guide-chromium/storage/localstorage#delete-all-localstorage-key-value-pairs-for-a-domain

For example, for me, the following is displayed:
![grafik](https://github.com/magicsunday/webtrees-pedigree-chart/assets/564393/830737ea-d9c9-4e43-a9b9-adfdb168931c)

**Comment by HRN65** [comment]
Deleting all localStorage key-value pairs for my domain fixed the problem.
Once again Thank you!
